# Generated by Django 4.1.3 on 2022-11-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_message_options_message_date_to_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users_online',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
